Fix CLI gameplay AttributeError for Display.print_message
Changed display.print_message() to display.show_message() at line 1162.

The Display class doesn't have a print_message() method - the correct
method name is show_message().

Error when running game with party:
  AttributeError: 'Display' object has no attribute 'print_message'

The run_game_with_party() function was using the wrong method name
while the regular run_game() function was using the correct one.